export const palettes = {
    orange: {
        name: 'Orange',
        c1: '#FFEDD5',
        c2: '#FFD6A5',
        c3: '#FFBB72',
        c4: '#FD943A',
        eye: '#3a1a08',
        cheek: '#FF6B7A',
        glow: '#FD943A',
    },
    sapphire: {
        name: 'Sapphire',
        c1: '#D6EBFF',
        c2: '#9CC9FF',
        c3: '#5AA0FF',
        c4: '#2563EB',
        eye: '#0a1530',
        cheek: '#FF6B9A',
        glow: '#2563EB',
    },
    amethyst: {
        name: 'Amethyst',
        c1: '#F0DBFF',
        c2: '#D2A6FF',
        c3: '#A56DFF',
        c4: '#7C3AED',
        eye: '#1a0a30',
        cheek: '#FF6BB5',
        glow: '#7C3AED',
    },
    emerald: {
        name: 'Emerald',
        c1: '#D6F8E0',
        c2: '#86EAB0',
        c3: '#3DCD7A',
        c4: '#059669',
        eye: '#062a18',
        cheek: '#FF8FA3',
        glow: '#10B981',
    },
    rose: {
        name: 'Rose',
        c1: '#FFE1ED',
        c2: '#FFA8C7',
        c3: '#FF6B9A',
        c4: '#EC4899',
        eye: '#3a0a1a',
        cheek: '#FFC0CB',
        glow: '#EC4899',
    },
} as const;

export type PaletteName = keyof typeof palettes;
export type Palette = (typeof palettes)[PaletteName];
